version: "3.7"

networks:
  web:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/Storage_smb/server_config/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    networks:
      web:
        ipv4_address: 172.21.1.3
    restart: unless-stopped


  mongo:
    image: andresvidal/rpi3-mongodb3
    container_name: mongo-unifi
    environment:
      MONGO_INITDB_ROOT_USERNAME: ubnt
      MONGO_INITDB_ROOT_PASSWORD: ubntmongopassword
      MONGO_INITDB_DATABASE: unifi
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    ports:
      - 27117:27017
    networks:
      web:
        ipv4_address: 172.21.1.2
    restart: unless-stopped
